export const ACTION_SET_ACCOUNT_INFO = 'ACTION_SET_ACCOUNT_INFO';
export const ACTION_SET_SESSION_LIST = 'ACTION_SET_SESSION_LIST';
export const ACTION_SET_FRIEND_LIST = 'ACTION_SET_FRIEND_LIST';
export const ACTION_SET_GROUP_LIST = 'ACTION_SET_GROUP_LIST';
export const ACTION_SET_FRIEND_APPLY_LIST = 'ACTION_SET_FRIEND_APPLY_LIST';
export const ACTION_SET_MESSAGE_LIST = 'ACTION_SET_MESSAGE_LIST';
export const ACTION_SET_CURRENT_TARGET = 'ACTION_SET_CURRENT_TARGET';
export const ACTION_SET_LOGIN_INFO = 'ACTION_SET_LOGIN_INFO';

export const ACTION_GET_ACCOUNT_INFO = 'ACTION_GET_ACCOUNT_INFO';
export const ACTION_GET_SESSION_LIST = 'ACTION_GET_SESSION_LIST';
export const ACTION_GET_FRIEND_LIST = 'ACTION_GET_FRIEND_LIST';
export const ACTION_GET_GROUP_LIST = 'ACTION_GET_GROUP_LIST';
export const ACTION_GET_FRIEND_APPLY_LIST = 'ACTION_GET_FRIEND_APPLY_LIST';
export const ACTION_GET_MESSAGE_LIST = 'ACTION_GET_MESSAGE_LIST';
export const ACTION_GET_CURRENT_TARGET = 'ACTION_GET_CURRENT_TARGET';
export const ACTION_GET_LOGIN_INFO = 'ACTION_GET_LOGIN_INFO';

export const ACTION_MERGE_SESSION_LIST = 'ACTION_MERGE_SESSION_LIST';
export const ACTION_MERGE_FRIEND_LIST = 'ACTION_MERGE_FRIEND_LIST';
export const ACTION_MERGE_GROUP_LIST = 'ACTION_MERGE_GROUP_LIST';
export const ACTION_MERGE_FRIEND_APPLY_LIST = 'ACTION_MERGE_FRIEND_APPLY_LIST';
export const ACTION_MERGE_MESSAGE_LIST = 'ACTION_MERGE_MESSAGE_LIST';

export const ACTION_CREATE_SESSION = 'ACTION_CREATE_SESSION';

export const ACTION_SEND_TEXT_MESSAGE = 'ACTION_SEND_TEXT_MESSAGE';

export const ACTION_ALLOW_FRIEND_APPLY = 'ACTION_ALLOW_FRIEND_APPLY';

export const TARGET_TYPE_SESSION = 'TARGET_TYPE_SESSION';
export const TARGET_TYPE_FRIEND = 'TARGET_TYPE_FRIEND';
export const TARGET_TYPE_GROUP = 'TARGET_TYPE_GROUP';
export const TARGET_TYPE_SESSION_BY_DETAIL = 'TARGET_TYPE_SESSION_BY_DETAIL';